# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.brew-zsh]
local = "/opt/homebrew/share/zsh/site-functions"
apply = ["fpath"]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.vi-mode]
github = "jeffreytse/zsh-vi-mode"
apply = ["zcompile-source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["zcompile-defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["zcompile-defer"]

[plugins.fash-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["zcompile-defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["zcompile-defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["zcompile-defer"]

[plugins.pnpm]
github = "ntnyq/omz-plugin-pnpm"

[plugins.custom-completions]
local = "~/.zsh/completions"
apply = ["fpath"]

[plugins.zfunctions]
github = "mattmc3/zfunctions"
apply = ["zcompile-defer"]

[plugins.user-functions]
local = "~/.config/zsh/functions"
apply = ["fpath"]

[templates]
# A template that compiles and then sources the plugin
zcompile-source = """
{% for file in files %}
  if [[ ! -f "{{ file }}.zwc" || "{{ file }}" -nt "{{ file }}.zwc" ]]; then
    zcompile "{{ file }}"
  fi
  source "{{ file }}"
{% endfor %}
"""

zcompile-defer = """
{% for file in files %}
  zsh-defer _smart_source "{{ file }}"
{% endfor %}
"""

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
