# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
# set -g terminal-overrides 'xterm:colors=256'
set-window-option -g xterm-keys on
# General configuration.
# $ tmux show-options -g
set -g history-limit 5000
set -g base-index 1
set -g display-time 5000
set -g repeat-time 1000
set -g status-keys vi
set -g status-utf8 on
set -g status-bg black
set -g status-fg white
set -g status-justify left
set -g status-interval 1
set -g status-left-length 15
set -g status-right-length 55
set -g default-terminal "screen-256color"
set -g status-left "#[fg=white,bright,bg=blue] Session #[fg=yellow,bright,bg=blue]#S #[default] |" # session-name
set -g status-right "#[fg=red,bright][ #[fg=cyan]#(cd ~/miiicasa;git branch --no-color | sed -e '/^[^*]/d' -e 's/* //') #[fg=red]]#[default] #[fg=yellow,bright] %Y-%m-%d #[fg=green]%H:%M:%S #[default]#[fg=magenta,bright]#[default]"
set-window-option -g mode-keys vi

# Configuration for each window.
# $ tmux show-window-options -g
setw -g utf8 on
setw -g window-status-format " #I$ #W "
setw -g window-status-current-format " #I$ #W "
setw -g window-status-current-bg yellow
setw -g window-status-current-fg blue
setw -g window-status-current-attr default

# Customization for key bindings.
# Check it using "C-a + ?".
## Make tmux like screen, using Ctrl+A
unbind C-b
set -g prefix ^A
bind a send-prefix

## Use h and v for splitting.
unbind %
unbind '"'
bind v split-window -h
bind | split-window -h
bind h split-window -v
bind - split-window -v

## Use C-Left C-Right for previous windows and next windows
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
unbind p
unbind n
bind -nr C-Left previous-window
bind -nr C-Right next-window

bind C-e command-prompt -p "message?" "run-shell \"tmux list-windows -t $(tmux display -p '#S') | cut -d: -f1 |xargs -I{} tmux send-keys -t $(tmux display -p '#S'):{} '%1'\""


## Use a for renaming the window prompt.
unbind ','
bind ` command-prompt -I '#W' "rename-window '%%'"
new -A -s main
neww
neww 'htop'
# neww -n 'glances' 'glances'
# neww 'pry'
# neww -n 'IPython3' 'ipython3'
select-window -t 1
