tap "almogbaku/tap"
tap "appleboy/tap"
tap "buo/cask-upgrade"
tap "debba/tabularis"
tap "devwhodevs/tap"
tap "dopplerhq/cli"
tap "gromgit/brewtils"
tap "hashicorp/tap"
tap "hettysoft/tap"
tap "iagooar/qqqa"
tap "jakehilborn/jakehilborn"
tap "jr-k/d4s"
tap "jwt-rs/jwt-ui"
tap "kgarner7/feishin"
tap "ksdme/tap"
tap "macos-fuse-t/cask"
tap "manaflow-ai/cmux"
tap "michel-kraemer/zsh-patina"
tap "muxy-app/tap"
tap "nikitabobko/tap"
tap "open-pencil/tap"
tap "oven-sh/bun"
tap "postrv/forgemax"
tap "raggi/ale"
tap "restatedev/tap"
tap "sassman/tap"
tap "sentrux/tap"
tap "surge-downloader/tap"
tap "unnecessary-special-projects/tap"
tap "wader/tap"
tap "wickenico/wailbrew"
tap "zippoxer/tap"

# Essential
brew "age"
brew "age-plugin-yubikey"
brew "atuin"
brew "chezmoi"
brew "direnv"
brew "fd"
brew "fnox"
brew "fzf"
brew "gh"
brew "git-extras"
brew "git-lfs"
brew "jnv"
brew "jq"
brew "lsd"
brew "macos-trash", link: true
brew "mas"
brew "mise"
brew "ouch"
brew "ripgrep"
brew "sheldon"
brew "starship"
brew "topgrade"
brew "xh"
brew "zoxide"
cask "ghostty"

# Recommended
brew "ast-grep"
brew "bat"
brew "bitwarden-cli"
brew "d2"
brew "difftastic"
brew "dufs"
brew "git-cliff"
brew "jj"
brew "lazygit"
brew "lazyjj"
brew "lazyssh"
brew "yazi"
cask "appcleaner"
cask "atuin-desktop"
cask "bruno"

# Languages and Development Tools
brew "biome"
brew "cargo-dist"
brew "cmake"
brew "composer"
brew "gleam"
brew "go"
brew "openjdk"
brew "php"
brew "pipx"
brew "pomsky"
brew "python@3.11"
brew "ruby"
brew "ruff"
brew "uv"
cask "android-platform-tools"
cask "android-studio"

# Others
brew "almogbaku/tap/dap"
brew "apko"
brew "appleboy/tap/codegpt"
brew "bob"
brew "bottom"
brew "brotli"
brew "btop"
brew "ca-certificates"
brew "caddy"
brew "certbot"
brew "clipboard"
brew "coder"
brew "cryptography"
brew "dive"
brew "docker", link: false
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper-ecr"
brew "dopplerhq/cli/doppler"
brew "dua-cli"
brew "duckdb"
brew "duti"
brew "exiftool"
brew "flatbuffers"
brew "fx"
brew "gallery-dl"
brew "git-xet"
brew "gnupg"
brew "graphviz"
brew "gromgit/brewtils/taproom"
brew "hadolint"
brew "helix"
brew "hettysoft/tap/hetty"
brew "hexyl"
brew "hf"
brew "htop"
brew "hwatch"
brew "hyperfine"
brew "iagooar/qqqa/qqqa"
brew "icu4c@76"
brew "imagemagick"
brew "iproute2mac"
brew "jakehilborn/jakehilborn/displayplacer"
brew "jr-k/d4s/d4s"
brew "jsongrep"
brew "just"
brew "jwt-rs/jwt-ui/jwt-ui"
brew "k6"
brew "ksdme/tap/ut"
brew "libomp", link: true
brew "libpq", link: true
brew "luarocks"
brew "mask"
brew "melange"
brew "michel-kraemer/zsh-patina/zsh-patina"
brew "mkcert"
brew "mold"
brew "mole"
brew "moon"
brew "mosh"
brew "mprocs"
brew "mycli"
brew "nss"
brew "opencode"
brew "oven-sh/bun/bun"
brew "pandoc"
brew "parallel"
brew "pgcli"
brew "pkgconf"
brew "poppler"
brew "postrv/forgemax/forgemax"
brew "prek"
brew "proto"
brew "pwgen"
brew "python-yq"
brew "radare2"
brew "rage"
brew "raggi/ale/openssl-osx-ca"
brew "rbw"
brew "rclone"
brew "restatedev/tap/restate"
brew "restatedev/tap/restate-server"
brew "rtk"
brew "sassman/tap/amoxide"
brew "sassman/tap/amoxide-tui"
brew "sccache"
brew "scrcpy"
brew "sentrux/tap/sentrux"
brew "snitch"
brew "step"
brew "svt-av1"
brew "syft"
brew "telnet"
brew "tokei"
brew "trippy"
brew "trufflehog"
brew "typos-cli"
brew "typst"
brew "typtea"
brew "unnecessary-special-projects/tap/ghist"
brew "viddy"
brew "wader/tap/fq"
brew "watch"
brew "watchman"
brew "wget"
brew "wireshark"
brew "woff2"
brew "xplr"
brew "yt-dlp"
brew "yubico-piv-tool"
brew "zippoxer/tap/recall"
cask "anytype"
cask "applite"
cask "audacity"
cask "bettercapture"
cask "cap"
cask "codex"
cask "context"
cask "cryptomator"
cask "cutter"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "debba/tabularis/tabularis"
cask "discord"
cask "docker-desktop"
cask "easy-move+resize"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-iosevka-nerd-font"
cask "fuse-t"
cask "github"
cask "hashicorp/tap/hashicorp-vagrant"
cask "imageoptim"
cask "iterm2"
cask "jellyfin-media-player"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "kdenlive"
cask "kekaexternalhelper"
cask "keycastr"
cask "kgarner7/feishin/feishin", trusted: true
cask "kid3"
cask "krita"
cask "logseq"
cask "lulu"
cask "macos-fuse-t/cask/fuse-t-sshfs"
cask "mediahuman-audio-converter"
cask "meld"
cask "minecraft"
cask "mole-app"
cask "muxy-app/tap/muxy"
cask "nikitabobko/tap/aerospace"
cask "notion"
cask "obs"
cask "opal-app"
cask "openineditor-lite"
cask "openinterminal-lite"
cask "orbstack"
cask "osaurus"
cask "puremac"
cask "raycast"
cask "selfcontrol"
cask "shortcat"
cask "silicon-app"
cask "slack"
cask "sourcetree"
cask "spectra-app"
cask "squirrel-app"
cask "stats"
cask "surge-downloader/tap/surge"
cask "synology-chat"
cask "synology-drive"
cask "tad"
cask "telegram"
cask "temurin"
cask "universal-android-debloater"
cask "vagrant"
cask "veracrypt-fuse-t"
cask "vivaldi"
cask "wailbrew"
cask "zoom"

mas "DaisyDisk", id: 411643860
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "LocalSend", id: 1661733229
mas "Numbers", id: 361304891
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pets Therapy", id: 1575542220
mas "Red Lines Tools", id: 1469400117
mas "RunCat", id: 1429033973
mas "Saber", id: 1671523739
mas "ScreenBrush", id: 1233965871
mas "Shareful", id: 1522267256
mas "TickTick", id: 966085870
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650

vscode "aaron-bond.better-comments"
vscode "ai-smith.nvim-ui-modes"
vscode "anthropic.claude-code"
vscode "astro-build.astro-vscode"
vscode "asvetliakov.vscode-neovim"
vscode "bodil.file-browser"
vscode "bradlc.vscode-tailwindcss"
vscode "bwya77.islands-dark"
vscode "copilotkit.copilotkit-vscode-extension"
vscode "esbenp.prettier-vscode"
vscode "fill-labs.dependi"
vscode "jock.svg"
vscode "julianiaquinandi.nvim-ui-modifier"
vscode "kewang.spek-vscode"
vscode "ms-azuretools.vscode-containers"
vscode "ms-vscode-remote.remote-containers"
vscode "myriad-dreamin.tinymist"
vscode "oxc.oxc-vscode"
vscode "redhat.vscode-yaml"
vscode "ripple-ts.ripple-ts-vscode-plugin"
vscode "rust-lang.rust-analyzer"
vscode "subframe7536.custom-ui-style"
vscode "unifiedjs.vscode-mdx"
vscode "visualjj.visualjj"

go "github.com/ayn2op/discordo"
go "github.com/jimschubert/delete-artifacts/cmd"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"

cargo "argus-cli"
cargo "skill-manager"

npm "corepack"
# vim: ft=ruby
