[tools]
python = "3.12"
node = "24"
cargo-binstall = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:golem-cli" = "latest"
"cargo:cargo-component" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:dotenvy" = "latest"
"cargo:flirt" = "latest"
"cargo:datatui" = "latest"
"cargo:cargo-sweep" = "latest"
"cargo:git-ignore-generator" = "latest"
"cargo:cargo-wasi" = "latest"
"cargo:dioxus-cli" = "latest"
"cargo:gitql" = "latest"
"cargo:jj-starship" = "latest"
"cargo:license-generator" = "latest"
"cargo:macocr" = "latest"
"cargo:parqeye" = "latest"
"cargo:pik" = "latest"
"cargo:run-kit" = "latest"
"cargo:rustowl" = "latest"
"cargo:sea-orm-cli" = "^2.0.0-rc"
"cargo:sendme" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:tealdeer" = "latest"
"cargo:try-rs" = "latest"
"cargo:typstfmt" = "latest"
"pipx:magika" = "latest"
"pipx:dotbins" = "latest"
"cargo:swab" = "latest"
"npm:agent-browser" = "latest"
"npm:@fission-ai/openspec" = "latest"
"cargo:https://github.com/chriskrycho/jj-gpc.git" = "latest"
"npm:add-skill" = "latest"
"npm:openskills" = "latest"
"cargo:claude-code-status-line" = "latest"
"pipx:oraios/serena" = "main"
"npm:happy-coder" = "latest"
"npm:@openai/codex" = "latest"
"pipx:basedpyright" = "latest"
claude-code = "latest"
"cargo:https://github.com/davidbeesley/claude-chill" = "latest"
"cargo:evcxr_repl" = "latest"
"npm:vercel" = "latest"
"npm:skills" = "latest"
"pipx:sqlit-tui" = { version = "latest", extra = "postgres,duckdb" }
"npm:@google/gemini-cli" = "latest"
"pipx:marimo" = { version = "latest", extra = "recommended,mcp" }
"npm:react-doctor" = "latest"
terraform = "latest"
"pipx:ipython" = "latest"
"npm:@open-pencil/mcp" = "latest"
"github:DanSnow/kn" = "latest"
"pipx:sherlock-project" = "latest"

[settings]

[settings.npm]
package_manager = "pnpm"
