# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  edit: 'avim {{filename}}'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
