#!/bin/zsh
##? try something

# Captures the output of the binary (stdout) which is the "cd" command
# The TUI is rendered on stderr, so it doesn't interfere.
local output
output=$(command try-rs "$@")

if [ -n "$output" ]; then
    eval "$output"
fi

# vim: ft=zsh sw=2 ts=2 et

